version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db_quiz_lms'
      MYSQL_USER: 'admin_hima'
      MYSQL_PASSWORD: 'Him@war128'
      MYSQL_ROOT_PASSWORD: 'Him@war128'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: ./php
    container_name: php_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx_webserver
    restart: unless-stopped
    ports:
      - "8080:80" # Port untuk akses web (jika diperlukan dari lokal server)
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_gui
    restart: unless-stopped
    ports:
      - "8081:80" # Port untuk akses phpMyAdmin
    environment:
      - PMA_HOST=db
    depends_on:
      - db
    networks:
      - app-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    restart: unless-stopped
    depends_on:
      - webserver
    networks:
      - app-network
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
